name: Binder
on:
  workflow_dispatch:
  push:
    branches:
    - main

# Push to dockerhub and cache on binder
jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_NREL_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_NREL_TOKEN }}
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true

    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.