name: pytest

on:
  push:
    branches:
    - main
    - development
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        env: [
          '--upgrade --upgrade-strategy=eager .[test]'
        ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ${{ matrix.env }}
      run: |
        python -m pip install --progress-bar off --upgrade pip
        python -m pip install --progress-bar off ${{ matrix.env }}
    - name: Test with pytest ${{ matrix.env }}
      run: |
        python -m pytest --cov=./ --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
