name: pytest

on:
  push:
    branches:
    - main
    - dev
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        env: [
          '--upgrade --upgrade-strategy=eager .[test]'
        ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ${{ matrix.env }}
      run: |
        python -m pip install --progress-bar off --upgrade pip
        python -m pip install --progress-bar off ${{ matrix.env }}
    - name: Test with pytest ${{ matrix.env }}
      run: |
        python -m pytest
